apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://localhost:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: navlori
      defaultBucket: async_data
    secureJsonData:
      token: navlori-influx-token-2026
