"""Orchestrator for the replay_collector controller.

Writes replay_config.json next to the controller and patches the chosen
world file so TIAGO++'s `controller` field points at "replay_collector".
Then prints instructions for opening Webots.

Usage (PowerShell, from repo root):
    .venv\\Scripts\\python.exe scripts\\run_replay.py \\
        --world  src/simulation/worlds/iln20_5d27099f_F2.wbt \\
        --dataset data/ronin_a000_intra \\
        --paths  0 \\
        --output data/ronin_a000_intra_replay
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
CONTROLLER_DIR = REPO_ROOT / "src" / "simulation" / "controllers" / "replay_collector"
CONFIG_PATH = CONTROLLER_DIR / "replay_config.json"


# ── world-file controller patch ──
TIAGO_RE = re.compile(
    r'(DEF TIAGO Tiago\+\+ \{[^}]*?\bcontroller )"([^"]*)"',
    re.DOTALL,
)


def parse_path_ids(spec: str) -> list[int]:
    """Parse "0", "0,2,4", "0-5", "0-3,7,9-12"."""
    out: list[int] = []
    for chunk in spec.split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        if "-" in chunk:
            lo, hi = chunk.split("-", 1)
            out.extend(range(int(lo), int(hi) + 1))
        else:
            out.append(int(chunk))
    return sorted(set(out))


def patch_world_controller(world: Path, target: str, dry_run: bool) -> tuple[bool, str]:
    text = world.read_text(encoding="utf-8")
    m = TIAGO_RE.search(text)
    if not m:
        return False, "no `DEF TIAGO Tiago++ { ... controller \"...\" ... }` found"
    current = m.group(2)
    if current == target:
        return True, f"already set to '{target}'"
    new_text = (text[:m.start()] + m.group(1) + f'"{target}"' + text[m.end():])
    if not dry_run:
        bak = world.with_suffix(world.suffix + ".bak-replay")
        shutil.copy2(world, bak)
        world.write_text(new_text, encoding="utf-8")
    return True, f"controller: '{current}' -> '{target}'"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--world", required=True, help="path to .wbt world")
    ap.add_argument("--dataset", required=True,
                    help="dataset root dir (containing path_NN subdirs)")
    ap.add_argument("--output", required=True,
                    help="output dir for replayed data")
    ap.add_argument("--paths", default="0",
                    help="path IDs spec, e.g. \"0\", \"0,2,4\", \"0-5\"")
    ap.add_argument("--gt-hz", type=float, default=10.0)
    ap.add_argument("--odom-hz", type=float, default=15.0)
    ap.add_argument("--camera-hz", type=float, default=5.0)
    ap.add_argument("--no-pose-anchor", action="store_true",
                    help="run with real differential-drive tracking; exact timing "
                         "only when path is feasible at TIAGO++'s wheel cap")
    ap.add_argument("--dry-run", action="store_true",
                    help="print what would happen; don't write config or patch world")
    args = ap.parse_args()

    world = Path(args.world).resolve()
    if not world.is_file():
        sys.exit(f"world not found: {world}")
    dataset = Path(args.dataset).resolve()
    if not dataset.is_dir():
        sys.exit(f"dataset dir not found: {dataset}")
    if not CONTROLLER_DIR.is_dir():
        sys.exit(f"replay_collector controller dir not found: {CONTROLLER_DIR}")

    pids = parse_path_ids(args.paths)
    if not pids:
        sys.exit("--paths produced empty list")

    # Identify dataset name for metadata
    dataset_name = dataset.name

    cfg = {
        "_doc": "Generated by scripts/run_replay.py - edit and reload Webots to change.",
        "dataset_dir": str(dataset).replace("\\", "/"),
        "output_dir":  str(Path(args.output).resolve()).replace("\\", "/"),
        "path_ids": pids,
        "world_dataset_id": dataset_name,
        "rates_hz": {
            "ground_truth_dense": args.gt_hz,
            "odometry": args.odom_hz,
            "camera": args.camera_hz,
        },
        "drive": {
            "dt_lookahead_s": 0.20,
            "k_v": 1.0,
            "k_yaw": 2.5,
            "k_lat": 0.8,
        },
        "feasibility": {
            "max_speed_m_s": 0.62,
            "max_yaw_rate_rad_s": 3.07,
        },
        "pose_anchor": not args.no_pose_anchor,
    }

    print(f"[run_replay] writing {CONFIG_PATH}")
    if args.dry_run:
        print(json.dumps(cfg, indent=2))
    else:
        CONFIG_PATH.write_text(json.dumps(cfg, indent=2), encoding="utf-8")

    print(f"[run_replay] patching {world.name} -> controller \"replay_collector\"")
    ok, msg = patch_world_controller(world, "replay_collector", args.dry_run)
    if not ok:
        sys.exit(f"  ERROR: {msg}")
    print(f"  {msg}")

    print()
    print("Next steps:")
    print(f"  1. Open Webots and load:  {world}")
    print( "  2. Press Play (top toolbar).")
    print( "  3. Watch the controller console for per-path progress.")
    print(f"  Output will land in:   {cfg['output_dir']}")
    if cfg["pose_anchor"]:
        print( "  Pose-anchor: ON (exact timing always; per-step delta sub-cm).")
    else:
        print( "  Pose-anchor: OFF (real diff-drive; only feasible paths exact-timed).")


if __name__ == "__main__":
    main()
