"""Orchestrator for the replay_collector controller.

Writes replay_config.json next to the controller and patches the chosen
world file so TIAGO++'s `controller` field points at "replay_collector".
Then prints instructions for opening Webots.

Usage (PowerShell, from repo root):
    .venv\\Scripts\\python.exe scripts\\run_replay.py \\
        --world  src/simulation/worlds/iln20_5d27099f_F2.wbt \\
        --dataset data/iln20_5d27099f_F2 \\
        --paths  0 \\
        --output data/iln20_5d27099f_F2_replay
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from replay_rig import ensure_replay_rig  # noqa: E402


REPO_ROOT = Path(__file__).resolve().parent.parent
CONTROLLER_DIR = REPO_ROOT / "src" / "simulation" / "controllers" / "replay_collector"
CONFIG_PATH = CONTROLLER_DIR / "replay_config.json"


def parse_path_ids(spec: str) -> list[int]:
    """Parse "0", "0,2,4", "0-5", "0-3,7,9-12"."""
    out: list[int] = []
    for chunk in spec.split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        if "-" in chunk:
            lo, hi = chunk.split("-", 1)
            out.extend(range(int(lo), int(hi) + 1))
        else:
            out.append(int(chunk))
    return sorted(set(out))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--world", required=True, help="path to .wbt world")
    ap.add_argument("--dataset", required=True,
                    help="dataset root dir (containing path_NN subdirs)")
    ap.add_argument("--output", required=True,
                    help="output dir for replayed data")
    ap.add_argument("--paths", default="0",
                    help="path IDs spec, e.g. \"0\", \"0,2,4\", \"0-5\"")
    ap.add_argument("--gt-hz", type=float, default=10.0)
    ap.add_argument("--odom-hz", type=float, default=15.0)
    ap.add_argument("--camera-hz", type=float, default=5.0)
    ap.add_argument("--no-pose-anchor", action="store_true",
                    help="run with real differential-drive tracking; exact timing "
                         "only when path is feasible at TIAGO++'s wheel cap")
    ap.add_argument("--fresh", action="store_true",
                    help="redo every listed path even if its _done.json exists "
                         "(default: resume -- completed paths are skipped)")
    ap.add_argument("--no-imu-profile", action="store_true",
                    help="disable the IMU-shaped speed profile (uniform "
                         "per-segment speed, the pre-4a behaviour)")
    ap.add_argument("--profile-v-max", type=float, default=2.5,
                    help="speed cap for the IMU profile's water-fill clip (m/s)")
    ap.add_argument("--dry-run", action="store_true",
                    help="print what would happen; don't write config or patch world")
    args = ap.parse_args()

    world = Path(args.world).resolve()
    if not world.is_file():
        sys.exit(f"world not found: {world}")
    dataset = Path(args.dataset).resolve()
    if not dataset.is_dir():
        sys.exit(f"dataset dir not found: {dataset}")
    if not CONTROLLER_DIR.is_dir():
        sys.exit(f"replay_collector controller dir not found: {CONTROLLER_DIR}")

    pids = parse_path_ids(args.paths)
    if not pids:
        sys.exit("--paths produced empty list")

    # Identify dataset name for metadata
    dataset_name = dataset.name

    # Pipeline invariant: the controller's world guard compares the OPEN
    # world's stem to the dataset dir name. Staging a mismatched pair would
    # be refused in Webots anyway -- fail here, at staging time, instead.
    if world.stem != dataset_name:
        sys.exit(f"world/dataset name mismatch: world '{world.stem}.wbt' vs "
                 f"dataset '{dataset_name}' -- the world guard requires them "
                 f"equal. Rebuild the world with --out-name {dataset_name}.")

    cfg = {
        "_doc": "Generated by scripts/run_replay.py - edit and reload Webots to change.",
        "dataset_dir": str(dataset).replace("\\", "/"),
        "output_dir":  str(Path(args.output).resolve()).replace("\\", "/"),
        "path_ids": pids,
        "world_dataset_id": dataset_name,
        "rates_hz": {
            "ground_truth_dense": args.gt_hz,
            "odometry": args.odom_hz,
            "camera": args.camera_hz,
        },
        "drive": {
            "dt_lookahead_s": 0.20,
            "k_v": 1.0,
            "k_yaw": 2.5,
            "k_lat": 0.8,
        },
        "feasibility": {
            "max_speed_m_s": 0.62,
            "max_yaw_rate_rad_s": 3.07,
        },
        "pose_anchor": not args.no_pose_anchor,
        "hover_m": 0.01,
        "resume": not args.fresh,
        "imu_speed_profile": not args.no_imu_profile,
        "imu_profile_v_max": args.profile_v_max,
        # Controller refuses to run if debug DEFs (ROBOT_PATHS/MARKER_*)
        # exist in the LOADED scene -- catches "world rebuilt on disk but
        # Webots still shows the old scene" (needs File > Reload World).
        "require_clean_world": True,
    }

    print(f"[run_replay] writing {CONFIG_PATH}")
    if args.dry_run:
        print(json.dumps(cfg, indent=2))
    else:
        CONFIG_PATH.write_text(json.dumps(cfg, indent=2), encoding="utf-8")

    print(f"[run_replay] ensuring kinematic REPLAY_RIG in {world.name}")
    ok, msg = ensure_replay_rig(world, args.dry_run)
    if not ok:
        sys.exit(f"  ERROR: {msg}")
    print(f"  {msg}")

    print()
    print("Next steps:")
    print(f"  1. Open Webots and load:  {world}")
    print( "  2. Press Play (top toolbar).")
    print( "  3. Watch the controller console for per-path progress.")
    print(f"  Output will land in:   {cfg['output_dir']}")
    if cfg["pose_anchor"]:
        print( "  Pose-anchor: ON (exact timing always; per-step delta sub-cm).")
    else:
        print( "  Pose-anchor: OFF (real diff-drive; only feasible paths exact-timed).")


if __name__ == "__main__":
    main()
